Repository astrandb/miele, pull requests merged in 2022-01, with the labels that each got.

#4 Next level
  README.md
  custom_components/miele/__init__.py
  custom_components/miele/binary_sensor.py
  custom_components/miele/climate.py
  custom_components/miele/config_flow.py
  custom_components/miele/const.py
  custom_components/miele/manifest.json
  custom_components/miele/pymiele.py
  custom_components/miele/sensor.py
  custom_components/miele/strings.json
  custom_components/miele/switch.py
  custom_components/miele/system_health.py
  custom_components/miele/translations/en.json
Labels: enhancement, maintenance

#11 Add many more sensors, enable translation of states, values etc
  custom_components/miele/__init__.py
  custom_components/miele/binary_sensor.py
  custom_components/miele/const.py
  custom_components/miele/devcap.py
  custom_components/miele/sensor.py
  custom_components/miele/translations/sensor.en.json
  custom_components/miele/translations/sensor.sv.json
  custom_components/miele/translations/sv.json
Labels: enhancement

#13 Add German translation
  custom_components/miele/translations/de.json
  custom_components/miele/translations/sensor.de.json
Labels: translation

#14 Update translations
  custom_components/miele/translations/sensor.en.json
  custom_components/miele/translations/sensor.sv.json
Labels: translation

#15 Add diagnostics capability
  custom_components/miele/diagnostics.py
Labels: enhancement
