Repository astrandb/miele, pull requests merged in 2022-02, with the labels that each got.

#17 Services and improved diagnostics
  custom_components/miele/__init__.py
  custom_components/miele/const.py
  custom_components/miele/diagnostics.py
  custom_components/miele/services.py
  custom_components/miele/services.yaml
Labels: enhancement, feature

#19 Update swedish translation
  custom_components/miele/translations/sensor.en.json
  custom_components/miele/translations/sensor.sv.json
Labels: enhancement

#21 More sensors and capture of status strings from API
  custom_components/miele/__init__.py
  custom_components/miele/binary_sensor.py
  custom_components/miele/diagnostics.py
  custom_components/miele/sensor.py
Labels: enhancement

#26 Temp sensors, and more
  README.md
  custom_components/miele/sensor.py
Labels: enhancement, bugfix, maintenance

#27 Update release template
  .github/release-drafter.yml
Labels: maintenance

#28 Add generic and raw service
  custom_components/miele/const.py
  custom_components/miele/services.py
  custom_components/miele/services.yaml
Labels: enhancement

#29 Use actions data for setup
  custom_components/miele/__init__.py
  custom_components/miele/climate.py
  custom_components/miele/sensor.py
Labels: enhancement

#41 Correct sensor descriptions
  custom_components/miele/sensor.py
Labels: bugfix

#43 Programs by device type
  custom_components/miele/const.py
  custom_components/miele/sensor.py
  custom_components/miele/translations/sensor.de.json
  custom_components/miele/translations/sensor.en.json
Labels: enhancement, translation

#44 Fan and Light entites
  custom_components/miele/__init__.py
  custom_components/miele/devcap.py
  custom_components/miele/fan.py
  custom_components/miele/light.py
Labels: enhancement, feature

#45 Add and cleanup docstrings
  custom_components/miele/__init__.py
  custom_components/miele/climate.py
  custom_components/miele/fan.py
  custom_components/miele/light.py
  custom_components/miele/services.py
  custom_components/miele/switch.py
  hacs.json
Labels: documentation, maintenance

#46 Make up Swedish translation
  custom_components/miele/translations/sensor.sv.json
Labels: translation

#47 Assortment of fixes
  custom_components/miele/const.py
  custom_components/miele/sensor.py
  custom_components/miele/translations/sensor.de.json
  custom_components/miele/translations/sensor.en.json
  custom_components/miele/translations/sensor.sv.json
Labels: enhancement, translation

#50 Move pymiele.py to pypi library
  custom_components/miele/__init__.py
  custom_components/miele/api.py
  custom_components/miele/const.py
  custom_components/miele/manifest.json
  custom_components/miele/pymiele.py
  custom_components/miele/system_health.py
Labels: enhancement

#51 Update development tools and docs
  Makefile
  README.md
  requirements-dev.txt
Labels: maintenance

#54 Cleanup extra_state_attributes and availability
  custom_components/miele/binary_sensor.py
  custom_components/miele/climate.py
  custom_components/miele/fan.py
  custom_components/miele/light.py
  custom_components/miele/sensor.py
  custom_components/miele/switch.py
Labels: enhancement

#55 Additional programs
  custom_components/miele/const.py
  custom_components/miele/translations/sensor.de.json
  custom_components/miele/translations/sensor.en.json
  custom_components/miele/translations/sensor.sv.json
Labels: translation

#56 Cleanup
  custom_components/miele/__init__.py
  custom_components/miele/config_flow.py
  custom_components/miele/const.py
  custom_components/miele/fan.py
  custom_components/miele/light.py
  custom_components/miele/switch.py
Labels: maintenance

#58 Use no_program for ID 0 even on dishwashers, add it for other device …
  custom_components/miele/const.py
Labels: enhancement
