Repository astrandb/miele, pull requests merged in 2022-12, with the labels that each got.

#161 Add dev container
  .devcontainer/.gitignore
  .devcontainer/configuration.yaml
  .devcontainer/devcontainer.json
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  README.md
  requirements-dev.txt
  requirements-devcontainer.txt
Labels: maintenance

#163 Tweak the dev container
  .devcontainer/devcontainer.json
Labels: maintenance

#169 Adjust API timeouts and various optimizations
  .devcontainer/configuration.yaml
  custom_components/miele/__init__.py
  custom_components/miele/climate.py
  custom_components/miele/config_flow.py
  custom_components/miele/const.py
  custom_components/miele/devcap.py
  custom_components/miele/diagnostics.py
  custom_components/miele/manifest.json
Labels: enhancement, maintenance

#172 Address some pylint issues
  custom_components/miele/fan.py
  custom_components/miele/light.py
  custom_components/miele/sensor.py
  custom_components/miele/vacuum.py
Labels: code quality

#173 Move debug statement to correct place
  custom_components/miele/climate.py
Labels: bugfix

#176 Add core temperature sensors to ovens
  custom_components/miele/sensor.py
Labels: enhancement

#183 Handle data decoding errors
  custom_components/miele/__init__.py
Labels: enhancement

#184 More robust error handling
  custom_components/miele/__init__.py
Labels: enhancement, code quality

#187 Add not charging program phase on robot vacuum cleaner
  custom_components/miele/const.py
  custom_components/miele/translations/sensor.de.json
  custom_components/miele/translations/sensor.en.json
  custom_components/miele/translations/sensor.nb.json
  custom_components/miele/translations/sensor.nl.json
  custom_components/miele/translations/sensor.sv.json
Labels: enhancement, translation

#185 Added Italian translation
  custom_components/miele/translations/it.json
  custom_components/miele/translations/sensor.it.json
Labels: translation

#186 Fix error on vacuum platform caused by wrong programID key
  custom_components/miele/vacuum.py
Labels: bugfix

#188 Add drying step sensor for tumble dryers and washer-dryers
  custom_components/miele/const.py
  custom_components/miele/sensor.py
  custom_components/miele/translations/sensor.de.json
  custom_components/miele/translations/sensor.en.json
  custom_components/miele/translations/sensor.nb.json
  custom_components/miele/translations/sensor.nl.json
  custom_components/miele/translations/sensor.sv.json
Labels: enhancement, translation

#190 Cleanup code
  custom_components/miele/climate.py
  custom_components/miele/devcap.py
  custom_components/miele/sensor.py
  custom_components/miele/vacuum.py
Labels: code quality

#191 Translations improvements
  custom_components/miele/const.py
  custom_components/miele/translations/it.json
  custom_components/miele/translations/sensor.de.json
  custom_components/miele/translations/sensor.en.json
  custom_components/miele/translations/sensor.it.json
  custom_components/miele/translations/sensor.nb.json
  custom_components/miele/translations/sensor.nl.json
  custom_components/miele/translations/sensor.sv.json
Labels: translation

#192 Consumption sensors reset
  custom_components/miele/const.py
  custom_components/miele/sensor.py
Labels: enhancement

#194 Coffee system support
  README.md
  custom_components/miele/__init__.py
  custom_components/miele/const.py
  custom_components/miele/devcap.py
  custom_components/miele/sensor.py
  custom_components/miele/translations/sensor.de.json
  custom_components/miele/translations/sensor.en.json
  custom_components/miele/translations/sensor.it.json
  custom_components/miele/translations/sensor.nb.json
  custom_components/miele/translations/sensor.nl.json
  custom_components/miele/translations/sensor.sv.json
Labels: feature, translation
