Repository astrandb/miele, pull requests merged in 2022-03, with the labels that each got.

#60 Support additional dishwasher program IDs
  custom_components/miele/const.py
  custom_components/miele/translations/sensor.de.json
  custom_components/miele/translations/sensor.en.json
Labels: enhancement, translation

#61 Power switch added to appliances that support it
  custom_components/miele/switch.py
Labels: bugfix, feature

#62 Improve "Generic action" service
  custom_components/miele/services.py
  custom_components/miele/services.yaml
Labels: bugfix

#63 Update Swedish translation
  custom_components/miele/translations/sensor.sv.json
Labels: translation

#64 Improve validation for generic action service
  custom_components/miele/services.py
  custom_components/miele/services.yaml
Labels: enhancement

#66 Support for set_program service
  custom_components/miele/manifest.json
  custom_components/miele/services.py
  custom_components/miele/services.yaml
Labels: feature

#65 Add list of supported programs to device diagnostics download
  custom_components/miele/diagnostics.py
Labels: feature

#70 Button platform for test
  custom_components/miele/__init__.py
  custom_components/miele/button.py
Labels: feature

#69 Missing comma
  custom_components/miele/services.py
Labels: bugfix

#73 Use constants instead of literals
  custom_components/miele/__init__.py
  custom_components/miele/button.py
  custom_components/miele/climate.py
  custom_components/miele/const.py
  custom_components/miele/diagnostics.py
  custom_components/miele/fan.py
  custom_components/miele/light.py
  custom_components/miele/services.py
  custom_components/miele/switch.py
  hacs.json
Labels: maintenance

#78 Representation of fan/light corrected
  custom_components/miele/const.py
  custom_components/miele/devcap.py
  custom_components/miele/fan.py
  custom_components/miele/light.py
Labels: bugfix

#75 Add sensors for ecoFeedback
  custom_components/miele/devcap.py
  custom_components/miele/sensor.py
Labels: enhancement
