Repository astrandb/miele, pull requests merged in 2023-03, with the labels that each got.

#230 Fix warning for non-numeric value
  custom_components/miele/sensor.py
Labels: bugfix

#240 Add new mappings for settings menu on coffee machine
  custom_components/miele/const.py
  custom_components/miele/strings.json
  custom_components/miele/translations/de.json
  custom_components/miele/translations/en.json
  custom_components/miele/translations/fr.json
  custom_components/miele/translations/it.json
  custom_components/miele/translations/nb.json
  custom_components/miele/translations/nl.json
  custom_components/miele/translations/sv.json
Labels: translation

#241 Add elapsed time sensor on robot vacuum cleaner
  custom_components/miele/sensor.py
Labels: enhancement

#239 Add Hungarian translation
  custom_components/miele/translations/hu.json
Labels: translation

#234 Add 7 as Auto program to dishwasher
  custom_components/miele/const.py
Labels: translation

#243 Add basic support for ambient light for hoods
  custom_components/miele/const.py
  custom_components/miele/light.py
Labels: enhancement
