Repository astrandb/miele, pull requests merged in 2023-10, with the labels that each got.

#339 Typos in README.md
  README.md
Labels: maintenance

#342 Lokalise: Translations update
  custom_components/miele/translations/bg.json
  custom_components/miele/translations/de.json
  custom_components/miele/translations/en.json
  custom_components/miele/translations/hu.json
  custom_components/miele/translations/it.json
  custom_components/miele/translations/nl.json
  custom_components/miele/translations/sv.json
Labels: translation

#343 Bump release to 0.1.16
  custom_components/miele/const.py
  custom_components/miele/manifest.json
  setup.cfg
Labels: skip-changelog

#351 Add device automation triggers and conditions
  custom_components/miele/device_condition.py
  custom_components/miele/device_trigger.py
  custom_components/miele/translations/en.json
Labels: enhancement
