Repository astrandb/miele, pull requests merged in 2023-11, with the labels that each got.

#357 Add 6 zone Induction Hob
  .pre-commit-config.yaml
  custom_components/miele/__init__.py
  custom_components/miele/binary_sensor.py
  custom_components/miele/devcap.py
  custom_components/miele/number.py
  custom_components/miele/translations/en.json
  custom_components/miele/translations/sv.json
Labels: enhancement

#358 Lokalise: Translations update
  custom_components/miele/translations/bg.json
  custom_components/miele/translations/de.json
  custom_components/miele/translations/en.json
  custom_components/miele/translations/fr.json
  custom_components/miele/translations/hu.json
  custom_components/miele/translations/it.json
  custom_components/miele/translations/nb.json
  custom_components/miele/translations/nl.json
  custom_components/miele/translations/sv.json
Labels: translation

#354 Show serial number on device page
  custom_components/miele/binary_sensor.py
  custom_components/miele/button.py
  custom_components/miele/climate.py
  custom_components/miele/fan.py
  custom_components/miele/light.py
  custom_components/miele/number.py
  custom_components/miele/sensor.py
  custom_components/miele/switch.py
  custom_components/miele/vacuum.py
Labels: enhancement

#370 Add error messages for Oauth2 in config_flow
  custom_components/miele/translations/en.json
Labels: enhancement

#362 Remove deprecated settings in dev container
  .devcontainer.json
Labels: development tools

#364 More robust startup
  custom_components/miele/climate.py
Labels: code quality

#373 Refactor representation of heat zones (plates) on hobs
  custom_components/miele/__init__.py
  custom_components/miele/devcap.py
  custom_components/miele/number.py
  custom_components/miele/translations/en.json
Labels: enhancement

#374 Lokalise: Translations update
  custom_components/miele/translations/bg.json
  custom_components/miele/translations/da.json
  custom_components/miele/translations/de.json
  custom_components/miele/translations/en.json
  custom_components/miele/translations/hu.json
  custom_components/miele/translations/it.json
  custom_components/miele/translations/nb.json
  custom_components/miele/translations/nl.json
  custom_components/miele/translations/sk.json
  custom_components/miele/translations/sv.json
Labels: translation

#375 Use localized name of appliance device type if available
  custom_components/miele/__init__.py
Labels: enhancement, translation

#378 SteamOvenPrograms1
  custom_components/miele/const.py
  custom_components/miele/devcap.py
Labels: enhancement

#380 Program IDs for DGC7450 steam oven
  custom_components/miele/const.py
  custom_components/miele/translations/en.json
Labels: enhancement

#383 Lokalise: Translations update
  custom_components/miele/translations/da.json
  custom_components/miele/translations/de.json
  custom_components/miele/translations/en.json
  custom_components/miele/translations/sk.json
  custom_components/miele/translations/sv.json
Labels: translation

#387 Improved detection of number of heat zones
  custom_components/miele/devcap.py
  custom_components/miele/number.py
Labels: bugfix

#388 Lokalise: Translations update
  custom_components/miele/translations/hu.json
Labels: translation

#228 Add large_pillows tumble dryer program
  custom_components/miele/const.py
  custom_components/miele/translations/en.json
Labels: additional info requested
