Repository astrandb/miele, pull requests merged in 2024-01, with the labels that each got.

#413 Remove strings.json as not used in custom_components
  custom_components/miele/strings.json
Labels: code quality

#421 Adjust pylint rules
  pyproject.toml
Labels: code quality, development tools

#423 Catch more HTTP errors and show better log messages
  .pre-commit-config.yaml
  custom_components/miele/__init__.py
Labels: bugfix

#422 Change from VacuumEntityDescription to StateVacuumEntityDescription to support HA2024.02
  custom_components/miele/vacuum.py
Labels: bugfix, dependency

#424 Lokalise: Translations update
  custom_components/miele/translations/fr.json
  custom_components/miele/translations/it.json
  custom_components/miele/translations/sk.json
  custom_components/miele/translations/sv.json
Labels: translation

#425 Change versioning to CalVer
  Makefile
  custom_components/miele/const.py
  custom_components/miele/manifest.json
  setup.cfg
Labels: maintenance
