Repository astrandb/miele, pull requests merged in 2024-08, with the labels that each got.

#518 Fix setting of target temp in climate entity
  custom_components/miele/climate.py
Labels: bugfix

#519 Use constants in climate entity definition
  custom_components/miele/climate.py
Labels: code quality

#521 Lokalise: Translations update
  custom_components/miele/translations/de.json
  custom_components/miele/translations/es.json
  custom_components/miele/translations/fr.json
  custom_components/miele/translations/lb.json
  custom_components/miele/translations/zh_CN.json
Labels: translation

#524 Bump ruff to 0.5.6
  .pre-commit-config.yaml
Labels: dependency, development tools

#522 Use common entity class
  custom_components/miele/binary_sensor.py
  custom_components/miele/button.py
  custom_components/miele/climate.py
  custom_components/miele/entity.py
  custom_components/miele/fan.py
  custom_components/miele/light.py
  custom_components/miele/number.py
  custom_components/miele/sensor.py
  custom_components/miele/switch.py
  custom_components/miele/vacuum.py
Labels: code quality

#525 Lint
  custom_components/miele/sensor.py
Labels: code quality

#523 Use translation placeholders for plate numbers
  custom_components/miele/number.py
  custom_components/miele/translations/en.json
Labels: code quality

#526 Lokalise: Translations update
  custom_components/miele/translations/bg.json
  custom_components/miele/translations/da.json
  custom_components/miele/translations/de.json
  custom_components/miele/translations/es.json
  custom_components/miele/translations/fi.json
  custom_components/miele/translations/fr.json
  custom_components/miele/translations/hu.json
  custom_components/miele/translations/it.json
  custom_components/miele/translations/lb.json
  custom_components/miele/translations/nb.json
  custom_components/miele/translations/nl.json
  custom_components/miele/translations/sk.json
  custom_components/miele/translations/sv.json
  custom_components/miele/translations/zh_CN.json
Labels: translation

#528 Fix HA 2024.8 compatibility
  custom_components/miele/fan.py
  hacs.json
Labels: bugfix

#530 Use MieleAppliance enum
  custom_components/miele/binary_sensor.py
  custom_components/miele/button.py
  custom_components/miele/climate.py
  custom_components/miele/const.py
  custom_components/miele/fan.py
  custom_components/miele/light.py
  custom_components/miele/number.py
  custom_components/miele/sensor.py
  custom_components/miele/switch.py
  custom_components/miele/vacuum.py
Labels: code quality
