Repository astrandb/miele, pull requests merged in 2024-05, with the labels that each got.

#474 Support removal of stale devices
  custom_components/miele/__init__.py
Labels: duplicate

#484 Lokalise: Translations update
  custom_components/miele/translations/es.json
  custom_components/miele/translations/fi.json
  custom_components/miele/translations/it.json
Labels: translation

#487 Update ruff rules to 4.5 and fix subsequent suggestions
  .pre-commit-config.yaml
  .ruff.toml
  custom_components/miele/binary_sensor.py
  custom_components/miele/button.py
  custom_components/miele/climate.py
  custom_components/miele/device_trigger.py
  custom_components/miele/diagnostics.py
  custom_components/miele/fan.py
  custom_components/miele/light.py
  custom_components/miele/sensor.py
  custom_components/miele/switch.py
  custom_components/miele/vacuum.py
Labels: code quality, development tools
